# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-mavsdk"
BBFILE_PATTERN_meta-mavsdk = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-mavsdk = "6"

LAYERDEPENDS_meta-mavsdk = "core"
LAYERSERIES_COMPAT_meta-mavsdk = "wrynose"
